# Generated by Django 4.1.5 on 2023-01-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=30)),
                ('mob', models.PositiveBigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('loc', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=20)),
                ('qty', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
