# Generated by Django 4.1.5 on 2023-01-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
