# Generated by Django 4.1.5 on 2023-01-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_products_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='customer',
            field=models.ManyToManyField(related_name='customers', to='app2.customer'),
        ),
    ]
